services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blogapi-app
        restart: unless-stopped
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./node_modules:/var/www/html/node_modules
        ports:
            - "8082:80"
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: blogapi-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USERNAME: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
